local f = io.open('sudo.lua', "rb")
local content = f:read("*all")
f:close()
os.execute('killall -9 sinchi.sh')
os.execute('killall -9 tg')
os.execute('rm -rf bot.lua')
os.execute('git reset --hard origin/master')
os.execute('git pull')
local fi = io.open('sudo.lua', "w+")
fi:write(tostring(content))
fi:close()
os.execute('chmod 777 tg && chmod 777 sinchi.sh')
os.execute('screen ./sinchi.sh')
